###
GET http://[::1]:8000/employees

# OR

###
GET http://[::]:8000/employees


# Localhost Address
# for IPV4 -> IPv4 address for localhost is 127.0.0.1 (loopback address). Actually, any IPv4 address in 127.0.0.0/8 is a loopback address.

# For IPv6 -> the direct analog of the loopback range is ::1/128. So ::1 (long form 0:0:0:0:0:0:0:1) is the one and only IPv6 loopback address.
# ::1 is the loopback address in IPv6.

# Within URLs
# Within a URL, use square brackets []:
# http://[::1]/
# Defaults to port 80.
# http://[::1]:80/
# Specify port.



# Ques. Finally, some comments were asking about ::/128 versus ::/0 versus ::.
# What is this difference ?

# Ans. Strictly speaking, the first two are CIDR notation not IPv6 addresses. They are actually specifying a range of IP addresses. A CIDR consists of a IP address and an additional number that specifies the number of bits in a netmask. The two together specify a range of addresses; i.e. the set of addresses formed by ignoring the bits masked out of the given address.

# So -> 
# :: means just the IPv6 address 0:0:0:0:0:0:0:0 
# ::/128 means 0:0:0:0:0:0:0:0 with a netmask consisting of 128 bits. This gives a network range with exactly one address in it.
# ::/0 means 0:0:0:0:0:0:0:0 with a netmask consisting of 0 bits. This gives a network range with 2128 addresses in it.; i.e. it is the entire IPv6 address space!