###
GET http://localhost:8000/api/v1/products

###
GET http://localhost:8000/api/v1/products/2


###
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
   "name" : "Acer Nitro 17",
   "price": 2199,
   "categoryId": 3
}


###
DELETE  http://localhost:8000/api/v1/products/4

###
PATCH http://localhost:8000/api/v1/products/3
Content-Type: application/json

{
   "name": "Ipad Pro Max",
   "price": 1399,
   "categoryId": 2
}

